### ISSUE TITLE
Compare with updated guidelines to make sure there's no conflicts

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#398]
Notify guidelines group of conflicts and discuss what to do.

---

Review existing validation rules:

- [x] [content files](https://github.com/nlbdev/epub3-guidelines-update/issues/82)
- [x] [references between the navigation document and the NCX](https://github.com/nlbdev/epub3-guidelines-update/issues/83)
- [x] [references between the navigation document and the content files](https://github.com/nlbdev/epub3-guidelines-update/issues/84)
- [x] [references between the OPF and the content files](https://github.com/nlbdev/epub3-guidelines-update/issues/85)
- [x] [the OPF](https://github.com/nlbdev/epub3-guidelines-update/issues/86)
- [x] [the structure of the content files](https://github.com/nlbdev/epub3-guidelines-update/issues/95)

Update validation rules based on feedback:

- [x] [content files](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/405) (assigned: none)
- [x] [references between the navigation document and the NCX](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/406) (assigned: none)
- [x] [references between the navigation document and the content files](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/392) (assigned: none)
- [x] [references between the OPF and the content files](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/407) (assigned: none)
- [x] [the OPF](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/408) (assigned: @hugovanversendaal)
- [x] [the structure of the content files](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/409) (assigned: none)

Note that references to `html:body[html:header]` refer to the single-HTML version of the books. You can remove these references, as we only need to validate the EPUB version now.

For reference, these links contain all the epubcheck error messages (if epubcheck validates something, we don't have to validate the same thing):

- [https://github.com/w3c/epubcheck/…/com/adobe/epubcheck/messages](https://github.com/w3c/epubcheck/tree/master/src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties)
- [https://github.com/w3c/epubcheck/…/com/adobe/epubcheck/util](https://github.com/w3c/epubcheck/tree/master/src/main/resources/com/adobe/epubcheck/util/messages.properties)
- [https://github.com/w3c/epubcheck/…/com/thaiopensource/datatype/xsd/resources](https://github.com/w3c/epubcheck/tree/master/src/main/resources/com/thaiopensource/datatype/xsd/resources/Messages.properties)
- [https://github.com/w3c/epubcheck/…/com/thaiopensource/relaxng/pattern/resources](https://github.com/w3c/epubcheck/tree/master/src/main/resources/com/thaiopensource/relaxng/pattern/resources/Messages.properties)
- [https://github.com/w3c/epubcheck/…/com/thaiopensource/validate/schematron/resources](https://github.com/w3c/epubcheck/tree/master/src/main/resources/com/thaiopensource/validate/schematron/resources/Messages.properties)
- [https://github.com/w3c/epubcheck/…/org/idpf/epubcheck/util/css](https://github.com/w3c/epubcheck/tree/master/src/main/resources/org/idpf/epubcheck/util/css/messages.properties)

---

Followup issue: [Make sure that everything in the new guidelines has a validation rule](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/397)
